### ISSUE TITLE
Wrong GitHub profile link

### ISSUE THREAD

**Issue by McPringle** [minicli/action-contributors#2]
After using your action (thank you very much for automating this task), the profile links in the `CONTRIBUTORS.md` are broken. They point to an API call instead of the profile page:

Actual: https://api.github.com/users/McPringle
Expected: https://github.com/McPringle

As a result, if the viewer of the file clicks on the GitHub username, he will get a JSON file instead of the expected profile page.

**Comment by McPringle** [comment]
I found the problem! I copied your example from the readme file which was using v3. After changing it manually to v3.1 the links are correct!

**Comment by Lewiscowles1986** [comment]
Still not 💯 what a user might expect. Perhaps scan the URI and nope out to prevent confusion; or just build the URI to the user profile...
